### ISSUE TITLE
UPnPError: 800 with SONOS Playlist including spotify track

### ISSUE THREAD

**Issue by lebrou34** [jeedom/plugin-sonos#2]
no issue if the SONOS PLAYLIST contains tracks from DEEZER but UPnPError when it contains songs from SPOTIFY.

**Comment by zoic21** [comment]
Hi,
It's not an jeedom issue, it's due to this lib : https://github.com/duncan3dc/sonos. I don't have spotify so I can not test or send log, can you open an issue to : https://github.com/duncan3dc/sonos.
